:Authors: William Rice, John Paul Brach
:Email: ricewilliam125@gmail.com
:Date: 10/29/21
:Revision: 0.0.1
:License: CC BY-NC-SA

= Project: Air Hockey Table

Code for an air hockey table.

== Step 1: Installation


== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a CC BY-NC-SA License.
This license lets others remix, adapt, and build upon your work non-commercially,
as long as they credit you and license their new creations under the identical terms.

=== Contributing
To contribute to this project please contact William Rice at ricewilliam125@gmail.com

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
