:Authors: William Rice, John Paul Brach
:Email: ricewilliam125@gmail.com
:Date: 10/29/21
:Revision: 0.0.1
:License: CC BY-NC-SA

= Project: Air Hockey Table

Code for an air hockey table.

== Step 1: Installation

Installed on an Arduino Nano R3

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Air-Hockey-Table         => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this text file
....

=== License
This project is released under a CC BY-NC-SA License.
This license lets others remix, adapt, and build upon your work non-commercially,
as long as they credit you and license their new creations under the identical terms.

=== Contributing
To contribute to this project please contact William Rice at ricewilliam125@gmail.com

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===
